### ISSUE TITLE
USER STORY: User Login

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Django-Blog#12]
As a **user** I can **login** so that **I can add a comment**

# Acceptance Criteria 
* The user can log in with a valid username and password.
* Passwords must be at least 8 characters long and contain at least one special character.

## Tasks
- [x] Implement the login form.
- [x] Validate user input on the login form.
- [x] Create a database schema for user data.

**Comment by AdrianaStoi** [comment]
Completed user story
